### ISSUE TITLE
Employee tracker

### ISSUE THREAD

**Issue by JaredMabus** [JaredMabus/employee-tracker#4]
# User Story:
A business owner wants to manage their company's departments, roles, and employees.

## Acceptance Criteria:
- [x] Prompt the user with the following options:
* SELECT: view all departments, view all roles, view all employees
* INSERT: add a department, add a role, and add an employee
* Update:  update an employee role
#### View
- [x] Choose view all departments > presented with a formatted table showing department names and department ids
- [x] Choose view all roles > job title, role id, the department that role belongs to, and the salary for that role
- [x] View all employees > employee ids, first names, last names, job titles, departments, salaries, and managers' first and last name
#### Add or Update
- [x] Add a new department > enter "name" of new department > added to db
- [x] Add a new role > enter name, salary, and department for the new role > added to db
- [x] add an employee > first name, last name, role, and manager > added to db
- [x] Update employee role > select an employee to update info for > updated in the db

## Task
- [x] User prompts
- [x] Controller functions
- [x] ascii title
